server:
  port: 12000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: consumerService
              uri: lb://consumer-service
              predicates:
                - Path=/cart/get/**
            - id: providerService
              uri: lb://provider-service
              predicates:
                - Path=/user/get/**

resilience4j:
  circuitbreaker:
    configs:
      default:
        wait-duration-in-open-state:
          seconds: 5
        failure-rate-threshold: 10
        minimum-number-of-calls: 1
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      breaker1:
        base-config: default

eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:13000/eureka/,http://localhost:13001/eureka/
