server:
  port: 10000
spring:
  application:
    name: consumer-service
eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:13000/eureka/,http://localhost:13001/eureka/
