server:
  port: 13000
spring:
  application:
    name: eureka-server
eureka:
  instance: #创建实例
    hostname: "eurekaService13000" #域名
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: "http://eurekaService13001:13001/eureka"