server:
  port: 10001
spring:
  application:
    name: consumer-service
eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:13000/eureka/,http://localhost:13001/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: TIME_BASED #有两种取值TIME_BASED, COUNT_BASED
        sliding-window-size: 10000 #滑动窗口的大小，单位ms
        minimum-number-of-calls: 5 #滑动窗口内最小请求个数为5
        failure-rate-threshold: 30 #失败率阈值，当请求失败率超过这个阈值时，Circuit Breaker会打开，单位%
        wait-duration-in-open-state: 5000 #断路器从打开到半开状态的等待时间
        permitted-number-of-calls-in-half-open-state: 3 #HALF_OPEN状态的时候，允许通过的请求个数
        event-consumer-buffer-size: 5
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.lang.Exception
        register-health-indicator: false
    instances:
      breakerA:
        base-config: default
      breakerB:
        base-config: default
        failure-rate-threshold: 50
        slow-call-rate-threshold: 30 #慢调用阈值
        slow-call-duration-threshold: 2000 #慢调用时间阈值